server:
  port: 7500

management:
  health:
    diskspace:
      enabled: false
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, matrics, beans, env, shutdown, loggers
  endpoint:
    health:
      show-details: always
  server:
    port: 7503

spring:

  main:
    allow-circular-references: true

  # security configuration
  security:
    user:
      name: user
      password: admin@123
    oauth2:
      client:
        registration:
          google:
            client-id: 382025911581-6c7r5k7ho9ef5vknn227fobrc8ltau0g.apps.googleusercontent.com
            client-secret: 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

  # database connection URL, username and password.
  datasource:
    url: jdbc:mysql://localhost:3306/learning_schema?useUnicode=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver 
    username: root
    password: root
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5

  # jpa configurations
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  # redis configurations
  data:
    redis:
      port: 6379
      host: 127.0.0.1

  # rabbitMq configurations
  rabbitMq:
    host: localhost
    port: 5672
    username: guest
    password: guest

JWT_SECRET_KEY: thisIsSpringBootLearningProject2025aaewer123235454rqwaawdh







 